[project]
name = "parser"
version = "0.1.0"
description = " Задача на прокачку №1"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "requests>=2.32.5",
]
